spring:
  datasource:
    url: jdbc:postgresql://db:5432/rmc_test
    username: postgres
    password: allTech
    hikari:
      max-lifetime: 300000
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 10
      maximum-pool-size: 20

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update


rmc-props:
  en-aes-key: L8P-56FV8^#Ek7kT
  encrypt-response: true
