#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: postgresql-pvc
#  namespace: rmc-be
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi

#// FOR KIND
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: rmc-be
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

