apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: rmc-be
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0001/
    type: DirectoryOrCreate